config/routes.rb
Rails.application.routes.draw do

  resources :companies

  root 'companies#index'

end

app/models/company.rb
class Company < ActiveRecord::Base
  has_many :connections
  has_many :contacts, through: :connections
  accepts_nested_attributes_for :connections
end

app/models/connection.rb
class Connection < ActiveRecord::Base
  belongs_to :company
  belongs_to :contact
  accepts_nested_attributes_for :contact
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  has_many :connections
  has_many :company, through: :connections
  accepts_nested_attributes_for :connections
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  def index
    @companies = Company.all
  end

  def show
  end

  def new
    @company = Company.new
    @connections = @company.connections.build
    @contacts = @connections.build_contact
  end

  def create
    @company = Company.new(company_params)
    if @company.save
      redirect_to companies_path
    else
      render 'new'
    end
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private

  def company_params
    params.require(:company).permit(:id, :name, connections_attributes: [:id, contact_attributes: [:id, :contact_number]])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_form.html.erb
<%= form_for(@company) do |company| %>
  <p>
    <%= company.label :name, "Company Name" %>
    <%= company.text_field :name %>
  </p>

  <%= company.fields_for :connections do |connection| %>
    <%= connection.fields_for :contact do |contact| %>
      <p>
        <%= contact.label :contact_number %>
        <%= contact.text_field :contact_number %>
      </p>
    <% end %>
  <% end %>

  <p>
    <%= company.submit 'Create' %>
  </p>
<% end %>

<%= link_to 'Back', companies_path %>

app/views/companies/create.html.erb
<h1>Companies#create</h1>
<p>Find me in app/views/companies/create.html.erb</p>

app/views/companies/destroy.html.erb
<h1>Companies#destroy</h1>
<p>Find me in app/views/companies/destroy.html.erb</p>

app/views/companies/edit.html.erb
<h1>Companies#edit</h1>
<p>Find me in app/views/companies/edit.html.erb</p>

app/views/companies/index.html.erb
<h1>Listing Company</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Contact Number</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @companies.each do |company| %>
      <tr>
        <td><%= company.name %></td>
        <td>
          <% company.connections.each do |connection| %>
            <%= connection.contact.contact_number %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Create Company', new_company_path %>

app/views/companies/new.html.erb
<h1>Create Company</h1>
<%= render 'form' %>

app/views/companies/show.html.erb
<h1>Companies#show</h1>
<p>Find me in app/views/companies/show.html.erb</p>

app/views/companies/update.html.erb
<h1>Companies#update</h1>
<p>Find me in app/views/companies/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tworedkites</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>